name: DeathExplosion
main: org.monstercraft.deathexplosion.DeathExplosion
version: 1.0
author: Fletch_to_99
description: Players that pay have a chance of exploding on death.
depend: [Vault, LWC]
commands:
  boom:
    description: Use /boom pay (amount)
    usage: Use /boom pay (amount)