name: DeathExplosion
main: org.monstercraft.deathexplosion.DeathExplosion
version: 1.0
author: Fletch_to_99
description: Players that pay have a chance of exploding on death.
softdepend: [Vault]
commands:
  boom:
    description: boom
    usage: /<command> [msg]